version: '3'
services:
  db:
    build:
      args:
        DB_SERVER_VERSION: ${DB_SERVER_VERSION}
      context: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  web:
    build:
      args:
        WEB_SERVER_VERSION: ${WEB_SERVER_VERSION}
        WEB_PHP_VERSION: ${WEB_PHP_VERSION}
      context: ./web/
    ports:
      - ${WEB_SERVER_PORT}:7080
      - ${WEB_HTML_PORT}:${WEB_HTML_EXPOSE_PORT}
    volumes:
      - ./web/lsws/admin/conf/:/usr/local/lsws/admin/conf/
      - ./web/lsws/conf/:/usr/local/lsws/conf/
