version: '3'
services:
  web:
    build:
      args:
        WEB_SERVER_VERSION: ${WEB_SERVER_VERSION}
        WEB_PHP_VERSION: ${WEB_PHP_VERSION}
      context: ./web/
    ports:
      - ${WEB_SERVER_PORT}:7080
      - ${WEB_HTML_PORT}:${WEB_HTML_EXPOSE_PORT}
